apiVersion: v1
data:
  config.json: |
        {
           "coreservice_ip": "10.0.0.10",
           "my_hostip": "10.0.0.10",
           "physical_location":{
                "longitude": 35,
                "latitude": 142
           },
           "site_id": "002",
           "logging":{
                "info":"stdout",
                "error":"stdout",
                "protocol": "stdout",
                "debug": "stdout"
           },
           "discovery": {
                "http_port": 80
           },
           "broker": {
                "http_port": 8060
           },
           "master": {
                "ngsi_agent_port": 1060
           },
           "worker": {
                "container_management": "kubernetes", 
                "container_autoremove": false,
                "start_actual_task": true,
                "capacity": 4
           },
           "designer": {
                "webSrvPort": 8080,
                "agentPort": 1030
           },
           "rabbitmq": {
                "port": 5672,
                "username": "admin",
                "password":"mypass"
           },
           "https": {
                "enabled" : false
           }
        }


kind: ConfigMap
metadata:
  name: edge-configmap
  resourceVersion: "v3.2.2"

