#apiVersion: v1
#kind: ServiceAccount
#metadata:
# namespace: fogflow
# name: default
#---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
 namespace: fogflow
 name: fogflow-dns-role-edge
rules:
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get","watch","list","create","delete"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get","watch","list","create","delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
 namespace: fogflow
 name: fogflow-dns-viewer-edge
roleRef:
 apiGroup: rbac.authorization.k8s.io
 kind: ClusterRole
 name: fogflow-dns-role-edge
subjects:
- kind: ServiceAccount
  namespace: fogflow
  name: edge

